### ISSUE TITLE
Inconsistency of implementation in Redpath

### ISSUE THREAD

**Issue by miaoxw** [DMTF/libredfish#160] opened 2022-12-01 03:39 UTC
Recently I am making some exploration for further use of `libredfish`. I tried to call `getPayloadByPath` after reading documents and README page,

In such an environment that contains one member of System, the redPath `/Systems` returns the payload below:

```
{
    "@odata.context":"/redfish/v1/$metadata#ComputerSystemCollection.ComputerSystemCollection",
    "@odata.id":"/redfish/v1/Systems",
    "@odata.type":"#ComputerSystemCollection.ComputerSystemCollection",
    "Description":"Collection of Computer Systems",
    "Members":[
        {
            "@odata.id":"/redfish/v1/Systems/System.Embedded.1"
        }
    ],
    "Members@odata.count":1,
    "Name":"Computer System Collection"
}
```

But when I tried to access its only member, `getPayloadByPath` returns NULL for error when I passed the redPath `/Systems/Members[1]`. In an occasional attempt, I got the right result with `/Systems/Members[0]`.

According to the freshly released [Redpath Specification](https://www.dmtf.org/sites/default/files/standards/documents/DSP0285_1.0.0.pdf), index is 1-based instead of 0-based in conventional programming language (JSON in this issue which caused the problem). This is also specially noted in the example query at line 102:

    * /Chassis[1]: Returns the first Chassis resource

Therefore I think implementation of redpath in the current version has conflicts with specification.

**#iwork4dell**

**Comment by mraineri** [comment] 2022-12-02 20:10
We might want to consider making an errata to the Redpath spec; the spec was intended to be based off libredfish, and 0-based indexing into JSON arrays seems more natural. Will need to discuss this others.

**Comment by dchanman** [comment] 2022-12-02 20:37
Errata works for Google, it turns out our current implementation was also 0-indexing.

**Comment by miaoxw** [comment] 2022-12-05 02:33
Our Redpath Specification says Redpath is based on XPath and XPath is 1-based. However, kepping the library as-is is indeed an option too.
Either implmementation makes sense. I think it is OK as long as lib and spec are consistent.

**Comment by mraineri** [comment] 2023-01-24 15:36
We've published an updated version of the RedPath spec to clarify the indexing is 0-based: https://www.dmtf.org/sites/default/files/standards/documents/DSP0285_1.0.1.pdf

> Selects the index number JSON entity from an array or object. For arrays, the index is 0-based.

**Comment by mraineri** [comment] 2023-01-24 15:40
Just updated the README:

> `/Chassis[0] - Will return the first Chassis instance`

@miaoxw if everything looks good at this point, I'd like to close the issue.

**Comment by miaoxw** [comment] 2023-01-31 02:59
@mraineri Hi Mike, it looks good to me now. You are safe to close this issue :)

**Closed** 2023-02-02 08:44 UTC
