### ISSUE TITLE
problem with sending requests

### ISSUE THREAD

**Issue by mmozejkx** [DMTF/libredfish#19] opened 2018-07-20 12:01 UTC
Hi,
I've built and run `examples/test.c` and it doesn't send any curl request.
It looks like the job is pushed to the queue but right after that `workItem->term` is set to `true` which ends up with job pop before calling curl send. 
I'll appreciate any help.

Ubuntu 16.04.4 LTS
commit:  4161c430e97f1e2391fdbda7035f1345304a5608

**Comment by mmozejkx** [comment] 2018-07-23 07:18
Hi,

Thanks for your response, now I see where the problem is

endpoint: `127.0.0.1:5000/redfish/v1/Chassis/Chassis-6`
```
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0x16e0ea0
addRequestHeader: Adding User-Agent => libredfish to 0x16e0ea0
asyncHeaderCallback: Adding Content-Type => text/html to (nil)
asyncHeaderCallback: Adding Content-Length => 233 to 0x7fa14c032310
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7fa14c032310
asyncHeaderCallback: Adding Date => Mon, 23 Jul 2018 06 to 0x7fa14c032310
rawAsyncWorkThread: Got response for url 127.0.0.1:5000/redfish with code 404
freeHeaders: Freeing 0x16e0ea0
freeHeaders: Freeing 0x7fa14c032310
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0x16e1450
addRequestHeader: Adding User-Agent => libredfish to 0x16e1450
asyncHeaderCallback: Adding Content-Type => text/html to (nil)
asyncHeaderCallback: Adding Content-Length => 233 to 0x7fa14c0327e0
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7fa14c0327e0
asyncHeaderCallback: Adding Date => Mon, 23 Jul 2018 06 to 0x7fa14c0327e0
rawAsyncWorkThread: Got response for url 127.0.0.1:5000/redfish/ with code 404
freeHeaders: Freeing 0x16e1450
freeHeaders: Freeing 0x7fa14c0327e0
```

I assume that at first `createServiceEnumerator()` pushes new job to query `/redfish`.
Here Redfish-Interface-Simulator throws 404 because service root is exposed at `/redfish/v1` not `/redfish`
Is there any way to change path of this initial query?

**Comment by mmozejkx** [comment] 2018-07-23 09:30
Now I see that libredfish is querying `/redfish` to enumerate present versions. Those were this two jobs pushed into a queue at start. Anyway, server responds with 404 which gives me clue that something may be wrong on simulator's side.

**Comment by pboyd04** [comment] 2018-07-23 14:18
You need to enable the workaround for a system that doesn't produce the version document. In the example test executable you can do this by adding "-W verdoc" to the commandline. This will send the flag down to createServiceEnumerator() telling it to ignore the version document and instead just assume v1.

**Comment by mmozejkx** [comment] 2018-07-24 10:06
Thanks.
It's not listed in "usage" that's why I've missed it :)

It would be great if it worked but not this time:) Unfortunately I'm getting really strange response:
```
rawAsyncWorkThread: Got response for url 127.0.0.1:5000/redfish/v1 with code 200
rawCallbackWrapper: Entered. request = 0xd95ae0, response = 0x7f712c028100, context = 0xd95ab0
Got a failure, httpCode = 65535
```
I'm gonna investigate this but in case you have faced this problem before, please let me know

**Comment by mraineri** [comment] 2018-08-02 21:44
Would like to close out this issue since it's a problem with the implementation not conforming to the spec (the lack of "/redfish" is illegal). Is it okay to close out this issue at this time?

**Comment by mmozejkx** [comment] 2018-08-07 12:18
I'm afraid that the problem described in my previous post is not related to version document missing. As you wrote before "-W verdoc" ommits version document and goes straight to "/redfish/v1". In this case it should work well.

**Comment by jautor** [comment] 2018-08-23 21:45
@mmozejkx do you mean that the issue is resolved, or is there something that still needs to be addressed?  (please close the issue if there's no longer an issue)

**Comment by mmozejkx** [comment] 2018-09-03 13:14
There is still an issue with getting response. As you can see above I get code 200 but later it throws an error no. 65535. I assume this is unexpected behaviour.

**Comment by pboyd04** [comment] 2018-09-04 14:14
@mmozejkx Can you provide details about what server implementation is having this issue? I'm not able to reproduce this failure on my end.

**Comment by pboyd04** [comment] 2018-09-05 14:11
@mmozejkx I've created a branch which should hopefully provide enough extra debug prints to figure out what is going on. Can you sync your repo, checkout ExtraDebug branch, rebuild, and rerun?

**Comment by mmozejkx** [comment] 2018-09-06 09:26
@pboyd04
Tried to reproduce it using ExtraDebug branch, I use Redfish-Interface-Emulator to provide service.

```
# ./redfishtest -vvvvv -W verdoc -H 127.0.0.1:5000
createServiceEnumerator: Entered. host = 127.0.0.1:5000, rootUri = (null), auth = (nil), flags = 1
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0xb8af70
addRequestHeader: Adding User-Agent => libredfish to 0xb8af70
asyncHeaderCallback: Adding Content-Type => text/html; charset=utf-8 to (nil)
asyncHeaderCallback: Adding Content-Length => 273 to 0x7f8384032340
asyncHeaderCallback: Adding Location => http to 0x7f8384032340
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7f8384032340
asyncHeaderCallback: Adding Date => Thu, 06 Sep 2018 09 to 0x7f8384032340
asyncHeaderCallback: Adding Content-Type => application/json to 0x7f8384032340
asyncHeaderCallback: Adding Content-Length => 1106 to 0x7f8384032340
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7f8384032340
asyncHeaderCallback: Adding Date => Thu, 06 Sep 2018 09 to 0x7f8384032340
rawAsyncWorkThread: Got response for url 127.0.0.1:5000/redfish/v1 with code 200
rawCallbackWrapper: Entered. request = 0xba99a0, response = 0x7f8384028100, context = 0xba9970
gotServiceRootAsync: Entered. success = 1, httpCode = 0xc8, payload = 0x7f83840327f0, context = 0xba9940
(null)
freeHeaders: Freeing 0xb8af70
freeHeaders: Freeing 0x7f8384032340
```

```
# ./redfishtest -vvvvvv -W verdoc -H 127.0.0.1:5000 /redfish/v1/Chassis/
createServiceEnumerator: Entered. host = 127.0.0.1:5000, rootUri = (null), auth = (nil), flags = 1
addRequestHeader: Adding Accept => application/json to (nil)
addRequestHeader: Adding OData-Version => 4.0 to 0xf83f70
addRequestHeader: Adding User-Agent => libredfish to 0xf83f70
asyncHeaderCallback: Adding Content-Type => text/html; charset=utf-8 to (nil)
asyncHeaderCallback: Adding Content-Length => 273 to 0x7f663c032340
asyncHeaderCallback: Adding Location => http to 0x7f663c032340
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7f663c032340
asyncHeaderCallback: Adding Date => Thu, 06 Sep 2018 09 to 0x7f663c032340
asyncHeaderCallback: Adding Content-Type => application/json to 0x7f663c032340
asyncHeaderCallback: Adding Content-Length => 1106 to 0x7f663c032340
asyncHeaderCallback: Adding Server => Werkzeug/0.14.1 Python/2.7.12 to 0x7f663c032340
asyncHeaderCallback: Adding Date => Thu, 06 Sep 2018 09 to 0x7f663c032340
rawAsyncWorkThread: Got response for url 127.0.0.1:5000/redfish/v1 with code 200
rawCallbackWrapper: Entered. request = 0xfa2a90, response = 0x7f663c028100, context = 0xfa2a60
gotServiceRootAsync: Entered. success = 1, httpCode = 0xc8, payload = 0x7f663c0327f0, context = 0xfa2a30
getPayloadForPathAsync: Entered. payload = 0x7f663c0327f0, redpath = 0xfa2940
getPayloadByNodeNameAsync: Payload contains no element named redfishgotServiceRootAsync: Failed to get next path section immediately...Got a failure, httpCode = 65535
freeHeaders: Freeing 0xf83f70
freeHeaders: Freeing 0x7f663c032340
```

**Comment by pboyd04** [comment] 2018-09-06 14:37
@mraineri It looks like we've found a bug in the Redfish interface emulator. From these logs it is returning multiple Content-Type headers (one text/html and one application/json) and multiple Content-Length headers. It really shouldn't be doing that.

@mmozejkx I don't actually use a simulator to test this anymore, I'm using real implementations.

**Comment by pboyd04** [comment] 2018-09-06 15:14
Ah it's due to the weird way that the python stuff does redirects...

**Comment by pboyd04** [comment] 2018-09-06 16:07
Ok the Fix19 branch should handle this. Basically, the Redfish interface emulator redirects in ways most implementations don't so I hadn't seen that before. libredfish now handles this style of redirect with that change.

**Closed** 2018-09-06 21:42 UTC
